### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by suchmememanyskill** [suchmememanyskill/mesh-organiser#4]
Hi all,

I'm trying to make a flatpak out of this app, but i simply don't have enough knowledge about flatpak on how to package this correctly.

My attempt at a config .yml:

```yml
id: com.meshorganiser.app

runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk

command: mesh-organiser
finish-args:
  - --socket=wayland # Permission needed to show the window
  - --socket=fallback-x11 # Permission needed to show the window
  - --device=dri # OpenGL, not necessary for all projects
  - --share=ipc

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/suchmememanyskill/mesh-organiser/releases/download/v1.0.0/Mesh.Organiser_1.0.0_amd64.deb
        sha256: cba13fa8faebe4ff1e6059985816386049b48f7f9d1190d7adebf5201e1f5cd4
        only-arches: [x86_64] #This source is only used on x86_64 Computers
        # This path points to the binary file which was created in the .deb bundle.
        # Tauri also creates a folder which corresponds to the content of the unpacked .deb.
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/mesh-organiser /app/bin/mesh-organiser
      - install -Dm755 usr/bin/mesh-thumbnail /app/bin/mesh-thumbnail
      - install -Dm644 usr/share/applications/Mesh\ Organiser.desktop /app/share/applications/com.meshorganiser.app.desktop
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/mesh-organiser.png /app/share/icons/hicolor/128x128/apps/com.meshorganiser.app.png
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/mesh-organiser.png /app/share/icons/hicolor/32x32/apps/com.meshorganiser.app.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/mesh-organiser.png /app/share/icons/hicolor/256x256@2/apps/com.meshorganiser.app.png
```

But this configuration has many issues. Yes, the app does boot. But:
- I cannot export to folder
- I cannot open in slicer
- Hardware acceleration seems broken (app is very laggy)
- I cannot drag files in 

There's probably more issues, but i'm way out of my depth here.

Would someone who's more knowledgable mind helping out?
